### ISSUE TITLE
Error spam every millisecond.

### ISSUE THREAD

**Issue by se3ya** [Lauriichan/LC-FriendPatches#7]
### Not a mod compatibility issue

- [X] I confirm that the my issue is not related to compatibility issues with another mod

### Mod version

1.1.0

### Mod list

RosiePies-Gordion_Sect0-2.1.4
sfDesat-Celest-1.0.7
theMenagerie-LiminalPools-1.0.6
Dantor-Dantors_Mental_Hospital-1.2.2
Tolian-PsychSanctum-0.3.3
sfDesat-ViewExtension-1.1.0
AudioKnight-StarlancerAIFix-3.4.0
AudioKnight-StarlancerMoons-1.4.2
scoopy-Scoopys_Variety_Mod-1.2.0
Piggy-LC_Office-1.1.24
Boniato-Ganimedes-2.2.1
Major_And_Skiz-MoreInteriors-2.5.0
Badham_Mods-SCPFoundationDungeon-3.0.0
Zingar-Atlas_Abyss-1.1.8
KayNetsua-E_Gypt_Moon-2.0.15
Zingar-SecretLabs-3.3.7
ViViKo-MedicSuit-1.0.2
Spright-HEV_Yellow-1.0.0
Spright-HEV_Blue-1.0.1
Spright-HEV_Green-1.0.0
Dunn-HEV_Suit-1.2.0
kidcudilovers-CudisRealisticSuits-1.0.0
SpookyDookies-Spooky_Dookies_Glowsuits-1.1.8
MagicalFlyingPurpleTreeSquid-Drive_Suit-1.0.3
ViViKo-TrophySuit-1.0.2
TeamClark-RustHazmatSuit-1.0.0
ViViKo-AmongUsSuits-1.0.2
Kats-Some_Suits-1.0.6
Stoners-SpiderManSuitV2-1.2.0
ViViKo-BreakingBadHazmatSuit-1.0.3
Flamango-OmniMan_Base_Suits-1.0.0
yeahimliam-Peter_Griffin_Suit-1.0.1
ManiaBania-1000_Quota_Stare-1.0.0
TeamClark-SCP_Foundation_Suit-1.1.0
happyfrosty-FrostySuits-1.1.14
Hexnet111-SuitSaver-1.2.0
Verity-TooManySuits-1.0.8
Mhz-MoreHead-1.2.6
PlainBen-BensCosmetics-1.2.0
NiaNation-AbsasCosmetics-1.2.3
HGG-JigglePhysicsPlugin-1.1.2
notnotnotswipez-MoreCompany-1.9.0
Backrooms-Backrooms-0.1.3
Ozone-Runtime_Netcode_Patcher-0.2.5
ViViKo-BunkbedRevive-1.1.1
mattymatty-AsyncLoggers-1.6.2
Kirpichyov-EnemiesScanner-1.0.6
Nilaier-SniffinFarts-1.0.1
Poseidon-MaskRemover-1.0.0
MegaPiggy-EnumUtils-1.0.3
Owen3H-IntroTweaks-1.5.0
veri-ShipWindows_4K_Skybox-1.0.2
Epicool-InsanityRemastered-1.2.1
stefan750-LCUltrawide-1.1.1
Swaggies-BetterPaycheck-0.9.0
Goobius-Scary_Coil_Head-1.0.1
Piggy-MaskedAIRevamp-0.2.1
XuXiaolan-TheGiantSpecimens-1.9.0
Agutrot-MolesterLootBug_Fork-1.0.0
Lusacan1-CoilHeadMod-1.0.0
FlipMods-HotbarPlus-1.6.1
Frack9-DarkMist-1.3.0
Renegades-FlashlightToggle-1.5.0
BananaPuncher714-LethalQuantities-1.2.8
Sigurd-CSync-4.1.0
TestAccount666-RealBackroomsPatch-1.2.2
NomnomAB-RollingGiant-2.6.0
zealsprince-Locker-1.1.2
SylviBlossom-SmartItemSaving-1.2.1
IntegrityChaos-GraphicsAPI-1.0.0
Forellma-Bracken_Jammer-1.0.1
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
x753-Peepers-0.9.7
IntegrityChaos-LCCutscene-1.0.0
mrov-TerminalFormatter-0.1.2
monkes_mods-JumpDelayPatch-1.0.1
loaforc-loaforcsSoundAPI-1.0.10
SylviBlossom-TerminalConflictFix-1.2.2
Pinta-PintoBoy-2.0.0
Danos-LethalStats-0.9.5
saint_kendrick-Lethal_Doors-1.0.4
YourFurnace-CarpetSound-1.0.0
qwbarch-Mirage-1.4.0
fumiko-CullFactory-1.0.4
F4ilS4fe-MaskTheDead-1.0.5
Spyci-CozyImprovements-1.2.2
quackandcheese-ToggleMute-1.3.1
Jordo-NeedyCats-1.2.1
fumiko-BetterMonitor-0.1.3
SillySquad-TakeThatMaskOff-2.1.6
veri-ShipWindows-2.0.5
thej01-DynamicFallDamage-1.0.0
zealsprince-Malfunctions-1.8.3
thej01-LethalWeight-1.0.2
Financier-GhostGirlFearReset-1.0.1
mrov-LethalRichPresence-0.5.8
SweetOnion-LethalSnap-1.5.5
Coppertiel-MaskedEnemyOverhaulFork-3.2.0
AinaVT-LethalConfig-1.4.0
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
IAmBatby-LethalLevelLoader-1.1.6
OE_Tweaks-Possessed_Masks-2.1.1
Hardy-LCMaxSoundsFix-1.1.0
Zaggy1024-OpenBodyCams-1.3.0
SillySquad-Arachnophilia-1.8.1
BGN-PizzaTowerEscapeMusic-2.3.0
LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.6
Lordfirespeed-OdinSerializer-2022.11.9
Zaggy1024-PathfindingLagFix-1.2.1
TanmanG-Forest_Giant_Motionsense-1.0.2
xilophor-LethalNetworkAPI-2.1.6
mrov-WeatherTweaks-0.4.6
Scintesto-Monster_Plushies-1.2.8
Nyxchrono-DoorBreach-1.1.0
ShaosilGaming-GeneralImprovements-1.1.14
ModusInteractive-Lethal_Trading_Cards-1.0.3
Orion-DontBlink-1.1.1
eXish-Batteries-1.1.0
LethalResonance-LETHALRESONANCE-4.2.3
Woecust-Immersive_Visor-0.5.2
ViViKo-NoSellLimit-1.0.1
Dreamweave-CompanyBuildingEnhancements-2.6.0
CTNOriginals-CrossHair-1.1.2
AgentRev-ShootableMouthDogs-1.0.1
loaforc-FacilityMeltdown-2.5.1
LeKAKiD-SignalTranslatorAligner-1.1.0
Electric131-IsThisTheWayICame-1.1.4
taffyko-NiceChat-1.2.4
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
darmuh-ghostCodes-2.0.3
blink9803-DimmingFlashlights-1.0.1
darmuh-darmuhsTerminalStuff-3.0.4
NutNutty-SellTracker-1.2.1
akechii-DiscountAlert-2.3.0
Evaisa-HookGenPatcher-0.0.5
BepInEx-BepInExPack-5.4.2100
sunnobunno-LandMineFartReverb-1.0.3
bigmcnugget-VanillaContentExpansion-0.1.8
Crazybloglog-Horrifying_Bracken-2.0.0
Rune580-LethalCompany_InputUtils-0.7.4
TopraksuK-FreeBirdTotemRemixJester-1.0.1
Rozebud-FOV_Adjust-1.1.1
NotAtomicBomb-TerminalApi-1.5.2
SteamBlizzard-Tyler1Bracken-1.1.0
Electric131-OuijaBoard-1.5.3
EliteMasterEric-SlimeTamingFix-1.0.2
FutureSavior-Hold_Scan_Button-1.1.1
IntegrityChaos-Diversity-2.0.3
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
5Bit-VoiceHUD-1.0.4
EladNLG-EladsHUD-1.2.1
TwinDimensionalProductions-CoilHeadStare-1.0.9
thej01-FearOverhauled-1.1.0
BatTeam-LethalFashion-1.0.7
MetalPipeSFX-HornMoan-2.1.0
Pooble-LCBetterSaves-1.7.3
EliteMasterEric-Coroner-1.6.2
Suskitech-AlwaysHearActiveWalkies-1.4.5
sunnobunno-YippeeMod-1.2.4
tinyhoot-ShipLoot-1.1.0
x753-Mimics-2.5.0
kyxino-LethalUtilities-1.2.21
FlipMods-TooManyEmotes-2.1.4
x753-More_Suits-1.4.3
Evaisa-LethalLib-0.15.1
ViViKo-MoreMaterials-1.3.2
seechela-CustomLogoForMBLCP-1.0.2
seechela-MoreBrutalLCMoons-1.4.8
seechela-MoreBrutalLCCosmetics-1.3.9
seechela-MoreBrutalLethalCompanyMain-1.7.8
seechela-MoreBrutalLethalCompanyPlus-2.1.5
BMX-LobbyCompatibility-1.1.0
mattymatty-LobbyControl-2.3.6
Evaisa-FixPluginTypesSerialization-1.1.1
Alice-ScarletDevilMansion-1.3.7
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.4.0
KlutzyBubbles-BetterEmotes-1.4.5
Darkbrewery-Emblem-1.2.8

### Describe what happend

When you start the game it starts spamming this error non stop 

[Error  : Unity Log] MissingMethodException: Method not found: int .RoundManager.PlayRandomClip(UnityEngine.AudioSource,UnityEngine.AudioClip[],bool,single,int)
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)

### Reproduction steps

Launch Lethal Company - Host lobby and boom it spams this error

### Expected behavior

It shouldn't spam errors every millisecond.

### Media

![image](https://github.com/Lauriichan/LC-FriendPatches/assets/116365392/c113b82a-1c6b-4cac-81e7-80694474461c)

### Additional Information

Idk if that helps but when I disable only your dependency LethalConfig it fixes error spamming.

**Comment by Lauriichan** [comment]
Not related to FriendPatches.
Also FriendPatches doesn't require LethalConfig.

**Comment by Lauriichan** [comment]
Also please use a incompatibility report next time.
Something is not a bug as long as it doesn't happen without any other mods installed.
